export const MOROCCO_CITIES = [
  "Casablanca",
  "Rabat",
  "Fès",
  "Marrakech",
  "Tanger",
  "Agadir",
  "Meknès",
  "Oujda",
  "Kénitra",
  "Tétouan",
  "Salé",
  "Safi",
  "El Jadida",
  "Béni Mellal",
  "Nador",
  "Taza",
  "Settat",
  "Berrechid",
  "Khouribga",
  "Mohammedia",
  "Laâyoune",
  "Dakhla",
  "Guelmim",
  "Ouarzazate",
  "Errachidia",
  "Al Hoceima",
  "Larache",
  "Chefchaouen",
  "Asilah",
  "Essaouira",
  "Ifrane",
  "Benslimane",
  "Khémisset",
  "Tiznit",
  "Taroudant",
  "Azrou",
  "Midelt",
  "Tinghir",
  "Zagora",
  "Tan-Tan",
  "Sidi Kacem",
  "Souk El Arba",
  "Fnideq",
  "M'diq",
  "Martil",
  "Sidi Slimane",
  "Had Soualem",
  "Bouznika",
  "Ben Guerir",
  "Youssoufia",
  "Skhirat",
  "Témara",
  "Inezgane",
  "Ait Melloul",
  "Dcheira El Jihadia",
] as const;

export type MoroccoCity = (typeof MOROCCO_CITIES)[number];

export const POPULAR_STUDENT_CITIES = [
  {
    city: "Casablanca",
    image: "/cities/casablanca.jpg",
    universities: ["ESCA", "HEM", "ESITH", "ENCG Casablanca"],
  },
  {
    city: "Rabat",
    image: "/cities/rabat.jpg",
    universities: ["UM5", "INSEA", "ENSSUP", "INPT"],
  },
  {
    city: "Fès",
    image: "/cities/fez.jpg",
    universities: ["USMBA", "Université Al Qaraouiyine", "ENSA Fès"],
  },
  {
    city: "Marrakech",
    image: "/cities/marrakech.jpg",
    universities: ["UCA", "ENCG Marrakech", "ENSA Marrakech"],
  },
  {
    city: "Agadir",
    image: "/cities/agadir.jpg",
    universities: ["Ibn Zohr", "ENCG Agadir", "ENSA Agadir"],
  },
  {
    city: "Tanger",
    image: "/cities/tanger.jpg",
    universities: ["Abdelmalek Essaadi", "ENCG Tanger", "ENSA Tanger"],
  },
  {
    city: "Meknès",
    image: "/cities/meknes.jpg",
    universities: ["Université Moulay Ismail", "ENCG Meknès", "ENSA Meknès"],
  },
  {
    city: "Oujda",
    image: "/cities/oujda.jpg",
    universities: ["Université Mohammed Premier", "ENCG Oujda", "ENSA Oujda"],
  },
  {
    city: "Errachidia",
    image: "/cities/errachidia.jpg",
    universities: ["Université Moulay Ali Cherif", "ENSA Errachidia"],
  },
] as const;
